---
collections:
  - ansible.posix
  - community.docker

roles:
  - geerlingguy.docker
  - geerlingguy.pip
  - geerlingguy.security
  - name: wazuh.agent
    src: git+https://github.com/runitsolutions/wazuh-agent
    scm: git