---
- name: Converge
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: '[Pre] Update APT cache.'
      apt: update_cache=yes cache_valid_time=3600
      when: not ansible_check_mode

    - name: '[Pre] Rewrites variables for testing.'
      set_fact:
        dcc_repository_branch: 'docker-image'
        pip_install_packages: [docker-py]

  roles:
    - geerlingguy.docker
    - geerlingguy.pip
    - new