---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: false

  tasks:
    - name: '[Destroy] Destroy Molecule LXC instances.'
      lxd_container:
        name: '{{ item.name }}'
        state: absent
        force_stop: '{{ item.force_stop | default(true) }}'
      loop: '{{ molecule_yml.platforms }}'