---
- name: Verify
  hosts: all
  gather_facts: false
  vars_files: ../../defaults/main.yml

  tasks:
    - name: Verifies authorized_keys file exists.
      stat:
        path: '/home/{{ user_name }}/.ssh/authorized_keys'
      register: key_state
      failed_when: key_state.stat.exists | bool == false