---
- name: Verify if folder /tmp/docker_image_tmp exists.
  stat:
    path: /tmp/doker_image_tmp
  register: docker_image_tmp_result

- name: Remove folder /tmp/docker_image_tmp.
  file:
    path: /tmp/docker_image_tmp
    state: absent
    force: true
  when:
    - not ansible_check_mode
    - docker_image_tmp_result.stat.exists | bool
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"

- name: Build Docker image and optionally upload it to Dockerhub.
  block:
    - name: Clone repository.
      git:
        repo: '{{ docker_image_repository }}'
        dest: /tmp/docker_image_tmp
        single_branch: true
        version: '{{ docker_image_repository_branch }}'
      changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"

    - name: Compile Docker image.
      command: ./build-with-docker.sh
      args:
        chdir: /tmp/docker_image_tmp
      changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"

    - name: Build Docker image.
      docker_image:
        build:
          path: /tmp/docker_image_tmp/docker
        name: '{{ docker_image_name }}'
        source: build

    - block:
        - name: Log into DockerHub.
          docker_login:
            username: '{{ dockerhub_user }}'
            password: '{{ dockerhub_password }}'
            email: '{{ dockerhub_mail }}'

        - name: Push image to Dockerhub.
          docker_image:
            name: '{{ docker_image_name }}'
            repository: '{{ docker_image_name }}'
            push: true
            source: local
      when: dockerhub_image_push | bool
  when: >
    not ansible_check_mode and
    (dockerhub_image_pull is not defined
    or dockerhub_image_pull | bool == false)

- name: Pull image from Dockerhub.
  docker_image:
    name: '{{ docker_image_name }}'
    source: pull
  when:
    - not ansible_check_mode
    - dockerhub_image_pull is defined
    - dockerhub_image_pull | bool
