---
- name: Creates a new DCC Docker image and uploads it to Dockerhub.
  become: true
  connection: local 
  gather_facts: true
  hosts: localhost

  roles:
    - geerlingguy.docker
    - role: geerlingguy.pip
      pip_install_packages: [docker-py]
    - runitcr.dcc.image