---
- name: Applies server hardening.
  become: true
  gather_facts: true
  hosts: all

  roles:
    - runitcr.dcc.user
    - geerlingguy.security

- name: Installs Wazuh agent.
  become: true
  gather_facts: true
  hosts: all

  pre_tasks:
    - name: Install required packages.
      apt:
        name: gnupg
        state: present

    - name: Ensure wazuh group exists.
      group:
        name: wazuh
        state: present

    - name: Ensure wazuh user exists.
      user:
        name: wazuh
        state: present

  roles:
    - wazuh.agent
